name: Build PiCompose - Respeaker_lite - Linux-Voice-Assistant

on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-image-template.yml
    with:
      image-name: PiCompose_Respeaker-lite_Linux-Voice-Assistant
      stage-list: stage0 stage1 stage2 ./01-stage-picompose ./02-stage-audiodriver-respeaker_lite ./03-stage-linux-voice-assistant ./04-stage-finish
      compression: xz
      compression-level: 6
      custom-hostname: picompose
